-- =============================================================================
-- patch_invoices.sql — أنماط الفواتير، الفواتير، المناقلة، حركات المخزون
-- =============================================================================
-- يتطلب: patch_journal_dimensions.sql
-- التالي: patch_settlement_foundation.sql
-- =============================================================================

-- ---------------------------------------------------------------------------
-- أنماط الفواتير
-- ---------------------------------------------------------------------------

create table if not exists public.invoice_patterns (
  id uuid primary key default gen_random_uuid(),
  pattern_no int generated by default as identity,
  name_ar varchar(200) not null,
  name_en varchar(200) null,
  secrecy_level smallint not null default 0 check (secrecy_level between 0 and 4),
  direction varchar(10) not null
    check (direction in ('input', 'output')),
  commercial_kind varchar(30) not null,
  is_return boolean not null default false,
  is_opening_stock boolean not null default false,
  is_active boolean not null default true,
  sort_order int not null default 0,

  default_branch_id uuid null references public.branches(id) on delete set null,
  default_cost_center_id uuid null references public.cost_centers(id) on delete set null,
  default_currency_id uuid null references public.currencies(id) on delete set null,
  default_warehouse_id uuid null references public.warehouses(id) on delete set null,
  target_warehouse_id uuid null references public.warehouses(id) on delete set null,

  default_creditor_account_id uuid null references public.accounts(id) on delete set null,
  default_debtor_account_id uuid null references public.accounts(id) on delete set null,
  default_cost_account_id uuid null references public.accounts(id) on delete set null,
  default_inventory_account_id uuid null references public.accounts(id) on delete set null,
  default_discount_account_id uuid null references public.accounts(id) on delete set null,
  default_extra_account_id uuid null references public.accounts(id) on delete set null,
  default_commission_account_id uuid null references public.accounts(id) on delete set null,
  transfer_transit_account_id uuid null references public.accounts(id) on delete set null,
  inter_branch_account_id uuid null references public.accounts(id) on delete set null,
  inter_cc_account_id uuid null references public.accounts(id) on delete set null,
  paired_input_pattern_id uuid null references public.invoice_patterns(id) on delete set null,

  generate_journal boolean not null default true,
  auto_post boolean not null default false,
  cc_on_goods boolean not null default false,
  cc_on_party boolean not null default false,
  load_party_currency boolean not null default false,
  warehouse_movement boolean not null default false,

  pricing_material_mode varchar(30) null,
  pricing_cost_mode varchar(30) null,
  pricing_consumed_mode varchar(30) null,

  reference_settings jsonb not null default '{}'::jsonb,

  default_settlement_mode varchar(10) not null default 'credit'
    check (default_settlement_mode in ('credit', 'cash')),
  payment_terms_enabled boolean not null default false,
  default_payment_terms_days int null check (default_payment_terms_days is null or default_payment_terms_days >= 0),

  rounding_enabled boolean not null default false,
  rounding_target varchar(20) null
    check (rounding_target is null or rounding_target in ('invoice_total', 'line_amount', 'both')),
  rounding_mode varchar(10) null
    check (rounding_mode is null or rounding_mode in ('nearest', 'up', 'down')),
  rounding_step numeric(18, 4) null check (rounding_step is null or rounding_step > 0),

  numbering_start int not null default 1 check (numbering_start >= 1),
  numbering_prefix varchar(20) not null default 'INV',
  numbering_padding int not null default 4 check (numbering_padding between 1 and 8),
  numbering_include_year boolean not null default true,
  numbering_reset varchar(10) not null default 'yearly'
    check (numbering_reset in ('never', 'yearly', 'monthly')),

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_invoice_patterns_active_sort
  on public.invoice_patterns(is_active, sort_order);
create index if not exists idx_invoice_patterns_commercial_kind
  on public.invoice_patterns(commercial_kind);

-- ---------------------------------------------------------------------------
-- ترقيم per نمط
-- ---------------------------------------------------------------------------

create table if not exists public.invoice_pattern_sequences (
  pattern_id uuid primary key references public.invoice_patterns(id) on delete cascade,
  last_number int not null default 0 check (last_number >= 0),
  sequence_year int not null default extract(year from current_date)::int,
  sequence_month int not null default extract(month from current_date)::int,
  updated_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- شروط النمط (§8) — 1:1
-- ---------------------------------------------------------------------------

create table if not exists public.invoice_pattern_conditions (
  pattern_id uuid primary key references public.invoice_patterns(id) on delete cascade,
  require_party boolean not null default false,
  require_sales_rep boolean not null default false,
  require_cost_center boolean not null default false,
  require_receipt_no boolean not null default false,
  prevent_duplicate_receipt_no boolean not null default false,
  require_payment_terms boolean not null default false,
  require_warehouse boolean not null default false,
  require_color boolean not null default false,
  require_size boolean not null default false,
  require_source boolean not null default false,
  require_caliber boolean not null default false,
  updated_at timestamptz not null default now()
);

create table if not exists public.invoice_pattern_allowed_materials (
  pattern_id uuid not null references public.invoice_patterns(id) on delete cascade,
  material_id uuid not null references public.materials(id) on delete cascade,
  primary key (pattern_id, material_id)
);

create table if not exists public.invoice_pattern_allowed_categories (
  pattern_id uuid not null references public.invoice_patterns(id) on delete cascade,
  category_id uuid not null references public.material_categories(id) on delete cascade,
  primary key (pattern_id, category_id)
);

-- ---------------------------------------------------------------------------
-- مستندات المناقلة
-- ---------------------------------------------------------------------------

create table if not exists public.inventory_transfers (
  id uuid primary key default gen_random_uuid(),
  transfer_no varchar(40) not null unique,
  from_branch_id uuid not null references public.branches(id) on delete restrict,
  to_branch_id uuid not null references public.branches(id) on delete restrict,
  from_warehouse_id uuid not null references public.warehouses(id) on delete restrict,
  to_warehouse_id uuid not null references public.warehouses(id) on delete restrict,
  out_invoice_id uuid null,
  in_invoice_id uuid null,
  status varchar(25) not null default 'draft'
    check (status in (
      'draft', 'dispatched', 'in_transit', 'partially_received', 'received', 'cancelled'
    )),
  shipped_at timestamptz null,
  received_at timestamptz null,
  notes text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint inventory_transfers_distinct_branches check (from_branch_id <> to_branch_id)
);

create index if not exists idx_inventory_transfers_status on public.inventory_transfers(status);
create index if not exists idx_inventory_transfers_from_branch on public.inventory_transfers(from_branch_id);
create index if not exists idx_inventory_transfers_to_branch on public.inventory_transfers(to_branch_id);

-- ---------------------------------------------------------------------------
-- الفواتير
-- ---------------------------------------------------------------------------

create table if not exists public.invoices (
  id uuid primary key default gen_random_uuid(),
  pattern_id uuid not null references public.invoice_patterns(id) on delete restrict,
  invoice_no varchar(40) not null unique,
  invoice_date date not null,

  branch_id uuid not null references public.branches(id) on delete restrict,
  cost_center_id uuid null references public.cost_centers(id) on delete restrict,

  customer_id uuid null references public.customers(id) on delete restrict,
  vendor_id uuid null references public.vendors(id) on delete restrict,

  creditor_account_id uuid null references public.accounts(id) on delete restrict,
  debtor_account_id uuid null references public.accounts(id) on delete restrict,
  cost_account_id uuid null references public.accounts(id) on delete restrict,
  inventory_account_id uuid null references public.accounts(id) on delete restrict,
  discount_account_id uuid null references public.accounts(id) on delete restrict,
  extra_account_id uuid null references public.accounts(id) on delete restrict,
  commission_account_id uuid null references public.accounts(id) on delete restrict,
  transfer_transit_account_id uuid null references public.accounts(id) on delete restrict,

  reference_invoice_id uuid null references public.invoices(id) on delete restrict,
  inventory_transfer_id uuid null references public.inventory_transfers(id) on delete restrict,
  transfer_role varchar(5) null check (transfer_role is null or transfer_role in ('out', 'in')),

  settlement_mode varchar(10) not null default 'credit'
    check (settlement_mode in ('credit', 'cash')),
  payment_terms_days int null check (payment_terms_days is null or payment_terms_days >= 0),
  due_date date null,

  currency_id uuid null references public.currencies(id) on delete restrict,
  exchange_rate numeric(18, 6) null check (exchange_rate is null or exchange_rate > 0),
  receipt_no varchar(50) null,

  description text null,
  status varchar(20) not null default 'draft'
    check (status in ('draft', 'posted', 'cancelled')),
  journal_entry_id uuid null unique references public.journal_entries(id) on delete restrict,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint invoices_single_party check (
    not (customer_id is not null and vendor_id is not null)
  )
);

create index if not exists idx_invoices_pattern_id on public.invoices(pattern_id);
create index if not exists idx_invoices_status on public.invoices(status);
create index if not exists idx_invoices_date on public.invoices(invoice_date);
create index if not exists idx_invoices_branch_id on public.invoices(branch_id);
create index if not exists idx_invoices_customer_id on public.invoices(customer_id);
create index if not exists idx_invoices_vendor_id on public.invoices(vendor_id);
create index if not exists idx_invoices_inventory_transfer_id on public.invoices(inventory_transfer_id);
create unique index if not exists idx_invoices_receipt_no_unique
  on public.invoices(receipt_no)
  where receipt_no is not null and trim(receipt_no) <> '';

-- ربط المناقلة بالفواتير (بعد إنشاء invoices)
alter table public.inventory_transfers
  drop constraint if exists inventory_transfers_out_invoice_id_fkey;
alter table public.inventory_transfers
  add constraint inventory_transfers_out_invoice_id_fkey
  foreign key (out_invoice_id) references public.invoices(id) on delete set null;

alter table public.inventory_transfers
  drop constraint if exists inventory_transfers_in_invoice_id_fkey;
alter table public.inventory_transfers
  add constraint inventory_transfers_in_invoice_id_fkey
  foreign key (in_invoice_id) references public.invoices(id) on delete set null;

-- FK مصدر الفاتورة على أسطر القيد
alter table public.journal_entry_lines
  drop constraint if exists journal_entry_lines_source_invoice_id_fkey;
alter table public.journal_entry_lines
  add constraint journal_entry_lines_source_invoice_id_fkey
  foreign key (source_invoice_id) references public.invoices(id) on delete set null;

-- ---------------------------------------------------------------------------
-- أسطر المواد
-- ---------------------------------------------------------------------------

create table if not exists public.invoice_material_lines (
  id uuid primary key default gen_random_uuid(),
  invoice_id uuid not null references public.invoices(id) on delete cascade,
  line_no int not null check (line_no > 0),

  branch_id uuid not null references public.branches(id) on delete restrict,
  cost_center_id uuid null references public.cost_centers(id) on delete restrict,
  warehouse_id uuid not null references public.warehouses(id) on delete restrict,

  material_id uuid not null references public.materials(id) on delete restrict,
  material_unit_id uuid not null references public.material_units(id) on delete restrict,
  quantity numeric(18, 6) not null check (quantity > 0),
  quantity_base numeric(18, 6) not null check (quantity_base > 0),
  unit_price numeric(18, 4) not null default 0 check (unit_price >= 0),
  line_amount numeric(18, 2) not null default 0 check (line_amount >= 0),

  qty_shipped numeric(18, 6) null check (qty_shipped is null or qty_shipped >= 0),
  qty_received numeric(18, 6) null check (qty_received is null or qty_received >= 0),

  color varchar(50) null,
  size varchar(50) null,
  source varchar(100) null,
  caliber varchar(50) null,
  line_description text null,

  created_at timestamptz not null default now(),
  unique (invoice_id, line_no)
);

create index if not exists idx_invoice_material_lines_invoice_id
  on public.invoice_material_lines(invoice_id);
create index if not exists idx_invoice_material_lines_material_id
  on public.invoice_material_lines(material_id);
create index if not exists idx_invoice_material_lines_warehouse_id
  on public.invoice_material_lines(warehouse_id);

-- ---------------------------------------------------------------------------
-- أسطر الحسابات الإضافية
-- ---------------------------------------------------------------------------

create table if not exists public.invoice_account_lines (
  id uuid primary key default gen_random_uuid(),
  invoice_id uuid not null references public.invoices(id) on delete cascade,
  line_no int not null check (line_no > 0),

  branch_id uuid not null references public.branches(id) on delete restrict,
  cost_center_id uuid null references public.cost_centers(id) on delete restrict,
  account_id uuid not null references public.accounts(id) on delete restrict,
  side varchar(10) not null check (side in ('debit', 'credit')),
  amount numeric(18, 2) not null check (amount > 0),
  description text null,

  created_at timestamptz not null default now(),
  unique (invoice_id, line_no)
);

create index if not exists idx_invoice_account_lines_invoice_id
  on public.invoice_account_lines(invoice_id);
create index if not exists idx_invoice_account_lines_account_id
  on public.invoice_account_lines(account_id);

-- ---------------------------------------------------------------------------
-- أسطر مستند المناقلة
-- ---------------------------------------------------------------------------

create table if not exists public.inventory_transfer_lines (
  id uuid primary key default gen_random_uuid(),
  transfer_id uuid not null references public.inventory_transfers(id) on delete cascade,
  line_no int not null check (line_no > 0),
  material_id uuid not null references public.materials(id) on delete restrict,
  material_unit_id uuid not null references public.material_units(id) on delete restrict,
  qty_ordered numeric(18, 6) not null default 0 check (qty_ordered >= 0),
  qty_shipped numeric(18, 6) not null default 0 check (qty_shipped >= 0),
  qty_received numeric(18, 6) not null default 0 check (qty_received >= 0),
  unit_cost_at_ship numeric(18, 4) null check (unit_cost_at_ship is null or unit_cost_at_ship >= 0),
  out_line_id uuid null references public.invoice_material_lines(id) on delete set null,
  in_line_id uuid null references public.invoice_material_lines(id) on delete set null,
  unique (transfer_id, line_no)
);

create index if not exists idx_inventory_transfer_lines_transfer_id
  on public.inventory_transfer_lines(transfer_id);

-- ---------------------------------------------------------------------------
-- دفتر حركات المخزون (تتبع مع كل حركة)
-- ---------------------------------------------------------------------------

create table if not exists public.inventory_movements (
  id uuid primary key default gen_random_uuid(),
  movement_date date not null default current_date,
  material_id uuid not null references public.materials(id) on delete restrict,
  warehouse_id uuid not null references public.warehouses(id) on delete restrict,
  branch_id uuid not null references public.branches(id) on delete restrict,
  cost_center_id uuid null references public.cost_centers(id) on delete restrict,
  quantity_delta numeric(18, 6) not null,
  quantity_base_delta numeric(18, 6) not null,
  unit_cost numeric(18, 4) null check (unit_cost is null or unit_cost >= 0),
  total_cost numeric(18, 2) null,
  movement_kind varchar(30) not null
    check (movement_kind in (
      'sale', 'purchase', 'transfer_out', 'transfer_in',
      'return_sale', 'return_purchase', 'opening_stock', 'adjustment'
    )),
  source_type varchar(30) not null,
  source_id uuid not null,
  source_line_id uuid null,
  journal_line_id uuid null references public.journal_entry_lines(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists idx_inventory_movements_material_wh
  on public.inventory_movements(material_id, warehouse_id, movement_date);
create index if not exists idx_inventory_movements_source
  on public.inventory_movements(source_type, source_id);

-- ---------------------------------------------------------------------------
-- ترقيم الفواتير per نمط
-- ---------------------------------------------------------------------------

create or replace function public.format_invoice_no(
  p_prefix varchar,
  p_include_year boolean,
  p_year int,
  p_sequence int,
  p_padding int
)
returns varchar
language sql
immutable
as $$
  select case
    when p_include_year then
      p_prefix || '-' || p_year::text || '-' || lpad(p_sequence::text, p_padding, '0')
    else
      p_prefix || '-' || lpad(p_sequence::text, p_padding, '0')
  end;
$$;

create or replace function public.peek_invoice_no(p_pattern_id uuid)
returns varchar
language plpgsql
stable
set search_path = public
as $$
declare
  v_pattern public.invoice_patterns%rowtype;
  v_seq public.invoice_pattern_sequences%rowtype;
  v_year int := extract(year from current_date)::int;
  v_month int := extract(month from current_date)::int;
  v_next int;
begin
  select * into v_pattern from public.invoice_patterns where id = p_pattern_id;
  if not found then
    raise exception 'Invoice pattern not found.';
  end if;

  select * into v_seq from public.invoice_pattern_sequences where pattern_id = p_pattern_id;
  if not found then
    v_next := v_pattern.numbering_start;
  else
    v_next := v_seq.last_number + 1;
    if v_pattern.numbering_reset = 'yearly'
       and v_pattern.numbering_include_year
       and v_seq.sequence_year <> v_year then
      v_next := v_pattern.numbering_start;
    elsif v_pattern.numbering_reset = 'monthly'
       and (v_seq.sequence_year <> v_year or v_seq.sequence_month <> v_month) then
      v_next := v_pattern.numbering_start;
    end if;
  end if;

  return public.format_invoice_no(
    v_pattern.numbering_prefix,
    v_pattern.numbering_include_year,
    v_year,
    v_next,
    v_pattern.numbering_padding
  );
end;
$$;

create or replace function public.reserve_invoice_no(p_pattern_id uuid)
returns varchar
language plpgsql
set search_path = public
as $$
declare
  v_pattern public.invoice_patterns%rowtype;
  v_seq public.invoice_pattern_sequences%rowtype;
  v_year int := extract(year from current_date)::int;
  v_month int := extract(month from current_date)::int;
  v_next int;
  v_no varchar(40);
begin
  select * into v_pattern from public.invoice_patterns where id = p_pattern_id;
  if not found then
    raise exception 'Invoice pattern not found.';
  end if;

  insert into public.invoice_pattern_sequences (pattern_id)
  values (p_pattern_id)
  on conflict (pattern_id) do nothing;

  select * into v_seq
  from public.invoice_pattern_sequences
  where pattern_id = p_pattern_id
  for update;

  if v_pattern.numbering_reset = 'yearly'
     and v_pattern.numbering_include_year
     and v_seq.sequence_year <> v_year then
    v_seq.last_number := 0;
    v_seq.sequence_year := v_year;
  elsif v_pattern.numbering_reset = 'monthly'
     and (v_seq.sequence_year <> v_year or v_seq.sequence_month <> v_month) then
    v_seq.last_number := 0;
    v_seq.sequence_year := v_year;
    v_seq.sequence_month := v_month;
  end if;

  v_next := greatest(v_seq.last_number + 1, v_pattern.numbering_start);
  v_no := public.format_invoice_no(
    v_pattern.numbering_prefix,
    v_pattern.numbering_include_year,
    v_year,
    v_next,
    v_pattern.numbering_padding
  );

  update public.invoice_pattern_sequences
  set
    last_number = v_next,
    sequence_year = v_year,
    sequence_month = v_month,
    updated_at = now()
  where pattern_id = p_pattern_id;

  return v_no;
end;
$$;

grant execute on function public.peek_invoice_no(uuid) to anon, authenticated;
grant execute on function public.reserve_invoice_no(uuid) to anon, authenticated;

-- ---------------------------------------------------------------------------
-- محفزات: إنشاء شروط + تسلسل عند نمط جديد
-- ---------------------------------------------------------------------------

create or replace function public.invoice_patterns_after_insert()
returns trigger
language plpgsql
as $$
begin
  insert into public.invoice_pattern_conditions (pattern_id)
  values (new.id)
  on conflict (pattern_id) do nothing;

  insert into public.invoice_pattern_sequences (pattern_id, last_number)
  values (new.id, greatest(new.numbering_start - 1, 0))
  on conflict (pattern_id) do nothing;

  return new;
end;
$$;

drop trigger if exists trg_invoice_patterns_after_insert on public.invoice_patterns;
create trigger trg_invoice_patterns_after_insert
after insert on public.invoice_patterns
for each row execute function public.invoice_patterns_after_insert();

-- ---------------------------------------------------------------------------
-- محفزات: أسطر المواد — quantity_base + مبلغ السطر
-- ---------------------------------------------------------------------------

create or replace function public.invoice_material_lines_apply_quantities()
returns trigger
language plpgsql
as $$
declare
  v_factor numeric(18, 6);
begin
  if not exists (
    select 1 from public.material_units mu
    where mu.id = new.material_unit_id
      and mu.material_id = new.material_id
  ) then
    raise exception 'material_unit_id does not belong to material_id.';
  end if;

  new.quantity_base := public.material_quantity_to_base(new.material_unit_id, new.quantity);
  new.line_amount := round((new.quantity * new.unit_price)::numeric, 2);

  if exists (
    select 1 from public.warehouses w
    where w.id = new.warehouse_id
      and w.branch_id <> new.branch_id
  ) then
    raise exception 'warehouse branch must match line branch_id.';
  end if;

  return new;
end;
$$;

drop trigger if exists trg_invoice_material_lines_apply_quantities on public.invoice_material_lines;
create trigger trg_invoice_material_lines_apply_quantities
before insert or update on public.invoice_material_lines
for each row execute function public.invoice_material_lines_apply_quantities();

-- ---------------------------------------------------------------------------
-- محفزات: تحقق الفاتورة والطرف
-- ---------------------------------------------------------------------------

create or replace function public.invoices_validate_parties()
returns trigger
language plpgsql
as $$
declare
  v_customer_active boolean;
  v_vendor_active boolean;
begin
  if new.customer_id is not null then
    select is_active into v_customer_active from public.customers where id = new.customer_id;
    if not coalesce(v_customer_active, false) then
      raise exception 'Referenced customer must be active.';
    end if;
  end if;

  if new.vendor_id is not null then
    select is_active into v_vendor_active from public.vendors where id = new.vendor_id;
    if not coalesce(v_vendor_active, false) then
      raise exception 'Referenced vendor must be active.';
    end if;
  end if;

  if new.transfer_role is not null and new.inventory_transfer_id is null then
    raise exception 'transfer_role requires inventory_transfer_id.';
  end if;

  if new.settlement_mode = 'credit'
     and new.payment_terms_days is not null
     and new.due_date is null then
    new.due_date := new.invoice_date + new.payment_terms_days;
  end if;

  return new;
end;
$$;

drop trigger if exists trg_invoices_validate_parties on public.invoices;
create trigger trg_invoices_validate_parties
before insert or update on public.invoices
for each row execute function public.invoices_validate_parties();

-- ---------------------------------------------------------------------------
-- updated_at
-- ---------------------------------------------------------------------------

drop trigger if exists trg_invoice_patterns_updated_at on public.invoice_patterns;
create trigger trg_invoice_patterns_updated_at
before update on public.invoice_patterns
for each row execute function public.set_updated_at();

drop trigger if exists trg_invoice_pattern_conditions_updated_at on public.invoice_pattern_conditions;
create trigger trg_invoice_pattern_conditions_updated_at
before update on public.invoice_pattern_conditions
for each row execute function public.set_updated_at();

drop trigger if exists trg_invoice_pattern_sequences_updated_at on public.invoice_pattern_sequences;
create trigger trg_invoice_pattern_sequences_updated_at
before update on public.invoice_pattern_sequences
for each row execute function public.set_updated_at();

drop trigger if exists trg_invoices_updated_at on public.invoices;
create trigger trg_invoices_updated_at
before update on public.invoices
for each row execute function public.set_updated_at();

drop trigger if exists trg_inventory_transfers_updated_at on public.inventory_transfers;
create trigger trg_inventory_transfers_updated_at
before update on public.inventory_transfers
for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------

alter table public.invoice_patterns enable row level security;
alter table public.invoice_pattern_sequences enable row level security;
alter table public.invoice_pattern_conditions enable row level security;
alter table public.invoice_pattern_allowed_materials enable row level security;
alter table public.invoice_pattern_allowed_categories enable row level security;
alter table public.invoices enable row level security;
alter table public.invoice_material_lines enable row level security;
alter table public.invoice_account_lines enable row level security;
alter table public.inventory_transfers enable row level security;
alter table public.inventory_transfer_lines enable row level security;
alter table public.inventory_movements enable row level security;

-- أنماط الفواتير
drop policy if exists "invoice_patterns_select_all" on public.invoice_patterns;
create policy "invoice_patterns_select_all" on public.invoice_patterns
  for select to anon, authenticated using (true);
drop policy if exists "invoice_patterns_insert_all" on public.invoice_patterns;
create policy "invoice_patterns_insert_all" on public.invoice_patterns
  for insert to anon, authenticated with check (true);
drop policy if exists "invoice_patterns_update_all" on public.invoice_patterns;
create policy "invoice_patterns_update_all" on public.invoice_patterns
  for update to anon, authenticated using (true) with check (true);

-- جداول مساعدة للأنماط
drop policy if exists "invoice_pattern_sequences_select_all" on public.invoice_pattern_sequences;
create policy "invoice_pattern_sequences_select_all" on public.invoice_pattern_sequences
  for select to anon, authenticated using (true);
drop policy if exists "invoice_pattern_sequences_insert_all" on public.invoice_pattern_sequences;
create policy "invoice_pattern_sequences_insert_all" on public.invoice_pattern_sequences
  for insert to anon, authenticated with check (true);
drop policy if exists "invoice_pattern_sequences_update_all" on public.invoice_pattern_sequences;
create policy "invoice_pattern_sequences_update_all" on public.invoice_pattern_sequences
  for update to anon, authenticated using (true) with check (true);

drop policy if exists "invoice_pattern_conditions_select_all" on public.invoice_pattern_conditions;
create policy "invoice_pattern_conditions_select_all" on public.invoice_pattern_conditions
  for select to anon, authenticated using (true);
drop policy if exists "invoice_pattern_conditions_insert_all" on public.invoice_pattern_conditions;
create policy "invoice_pattern_conditions_insert_all" on public.invoice_pattern_conditions
  for insert to anon, authenticated with check (true);
drop policy if exists "invoice_pattern_conditions_update_all" on public.invoice_pattern_conditions;
create policy "invoice_pattern_conditions_update_all" on public.invoice_pattern_conditions
  for update to anon, authenticated using (true) with check (true);

drop policy if exists "invoice_pattern_allowed_materials_all" on public.invoice_pattern_allowed_materials;
create policy "invoice_pattern_allowed_materials_all" on public.invoice_pattern_allowed_materials
  for all to anon, authenticated using (true) with check (true);

drop policy if exists "invoice_pattern_allowed_categories_all" on public.invoice_pattern_allowed_categories;
create policy "invoice_pattern_allowed_categories_all" on public.invoice_pattern_allowed_categories
  for all to anon, authenticated using (true) with check (true);

-- الفواتير وأسطرها
drop policy if exists "invoices_select_all" on public.invoices;
create policy "invoices_select_all" on public.invoices
  for select to anon, authenticated using (true);
drop policy if exists "invoices_insert_all" on public.invoices;
create policy "invoices_insert_all" on public.invoices
  for insert to anon, authenticated with check (true);
drop policy if exists "invoices_update_all" on public.invoices;
create policy "invoices_update_all" on public.invoices
  for update to anon, authenticated using (true) with check (true);

drop policy if exists "invoice_material_lines_all" on public.invoice_material_lines;
create policy "invoice_material_lines_all" on public.invoice_material_lines
  for all to anon, authenticated using (true) with check (true);

drop policy if exists "invoice_account_lines_all" on public.invoice_account_lines;
create policy "invoice_account_lines_all" on public.invoice_account_lines
  for all to anon, authenticated using (true) with check (true);

-- المناقلة والمخزون
drop policy if exists "inventory_transfers_all" on public.inventory_transfers;
create policy "inventory_transfers_all" on public.inventory_transfers
  for all to anon, authenticated using (true) with check (true);

drop policy if exists "inventory_transfer_lines_all" on public.inventory_transfer_lines;
create policy "inventory_transfer_lines_all" on public.inventory_transfer_lines
  for all to anon, authenticated using (true) with check (true);

drop policy if exists "inventory_movements_select_all" on public.inventory_movements;
create policy "inventory_movements_select_all" on public.inventory_movements
  for select to anon, authenticated using (true);
drop policy if exists "inventory_movements_insert_all" on public.inventory_movements;
create policy "inventory_movements_insert_all" on public.inventory_movements
  for insert to anon, authenticated with check (true);
