
-- =============================================================================
-- اكتمل التثبيت
-- =============================================================================
-- 1. Supabase → Authentication → Providers → فعّل Email/Password
-- 2. متغيرات البيئة للتطبيق:
--      NEXT_PUBLIC_SUPABASE_URL
--      NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY
--    (اختياري للإنشاء من الواجهة) SUPABASE_SERVICE_ROLE_KEY
-- 3. افتح التطبيق → /login → سجّل أول مستخدم (يصبح admin تلقائياً)
-- 4. من /settings/users أدر المستخدمين، ومن /settings/permissions الصلاحيات
-- 5. من /settings/branches و /settings/accounting-periods الإعدادات الجديدة
-- 6. (اختياري) شغّل 03_test_cases.sql للتحقق من سيناريوهات القبض والصرف
-- =============================================================================
